import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'akarve' at '1/21/16 9:31 PM' with Gradle 2.1
 *
 * @author akarve, @date 1/21/16 9:31 PM
 */
public class TestChromePushUtils {
    @Test public void testSomeLibraryMethod() {
        //Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
